format = """
[â”Œâ”€â‡](bold green) $directory$git_branch$git_commit$git_state$git_status$golang$python$java$kotlin$nodejs\
(\n[â”‚](bold green)$kubernetes)\
(\n[â”‚](bold green)$aws)\
\n[â””â”€â‡](bold green) $cmd_duration$jobs$time$status$character"""

[kubernetes]
disabled = false
format = 'as [$symbol$context( \($namespace\))]($style)'

[status]
symbol = 'ğŸ”´ '
disabled = false

[jobs]
symbol = " âœ¦"
